
```{r}

eff = rnorm(mean=0.5, sd = 0.1, n=20)
sa <- eff %>% map(~almond_yield(temp_feb = 18.989, precip_jan = 4.789))

sa <- as.data.frame(sa)

tmp = map_df(sa,`[`, c("annual"))

head(tmp)

site2df = data.frame(year = tmp$annual$year, elect= tmp$annual$elect)



```

```{r}

first_parts <- list()
# Extract the first part of each sublist for each part of the general list
first_parts <- list()
for (j in 1:length(almond_yield_temp)) {
  sublist <- almond_yield_temp[[j]]
  first_part_sublist <- list()
  for (i in 1:20) {
    first_part_sublist[[i]] <- sublist[[i]][1]
  }
  first_parts[[j]] <- first_part_sublist
}

```


```{r}
precip <- sensitivty_dat_precip_longer$precip
temp <- sensitivty_dat_longer$temp
params <- cbind.data.frame(precip, temp)

results = parms %>% pmap(almond_yield, temp_feb = temp,  precip_jan = precip)
```

```{r}
nsamples = 300
deviation = 0.15
base_temp = 20
temp = rnorm(mean=base_temp, sd = deviation*base_temp, n=nsamples)

base_precip = 100
precip = rnorm(mean=base_precip, sd = deviation*base_precip, n=nsamples)

params = data.frame(temp, precip)

results = params %>% pmap(almond_yield)

mean_yield = map_df(as.data.frame(results), `[`, c("mean_yield"))

mean_yield = cbind.data.frame(mean_yield, parms)
```


# plotting Almond Yield anomolies as a function of temperature
```{r}
# plot sensitivity of parameter
ggplot(sensitivty_dat_longer, aes(year, yield_anom, group = year)) + 
  geom_boxplot() + 
  labs(y = "Almond Yield Anomalies in ton per acre") +
  ylim(0, 50)

```










